INSERT INTO cities(city, country)
VALUES
    ('Paris', 'France'),
    ('New York', 'USA'),
    ('Rome', 'Italy'),
    ('London', 'UK'),
    ('Tokyo', 'Japan'),
    ('Lisbon', 'Portugal'),
    ('Barcelona', 'Spain'),
    ('Honolulu', 'Hawaii'),
    ('Istanbul', 'Turkey'),
    ('Bangkok', 'Thailand'),
    ('Agra', 'India'),
    ('Cairo', 'Egypt'),
    ('Helsinki', 'Finland'),
    ('Ubud, Bali', 'Indonesia'),
    ('Berlin', 'Germany'),
    ('Shanghai', 'China'),
    ('Las Vegas', 'USA'),
    ('Jerusalem', 'Israel'),
    ('Venice', 'Italy'),
    ('Cape Town', 'South Africa'),
    ('Rio de Janerio', 'Brazil'),
    ('Singapore', 'Singapore'),
    ('Toronto', 'Canada'),
    ('Seoul', 'South Korea'),
    ('Casablanca', 'Morocco'),
    ('Mosco', 'Russia'),
    ('Sydney', 'Australia'),
    ('Lima', 'Peru'),
    ('Beijing', 'China'),
    ('Buenos Aires', 'Argentina'),
    ('Edinburgh', 'Scotland'),
    ('Los Angeles', 'USA'),
    ('Copenhagen', 'Denmark'),
    ('Osaka', 'Japan'),
    ('Auckland', 'New Zealand'),
    ('Mumbai', 'India'),
    ('Dubai', 'United Arab Emirates'),
    ('Munich', 'Germany'),
    ('Hong Kong', 'China'),
    ('Qarar', 'State of Qatar'),
    ('Seattle', 'USA'),
    ('Oslo', 'Norway'),
    ('Bath', 'UK'),
    ('Athens', 'Greece'),
    ('Vienna', 'Austria'),
    ('Madrid', 'Spain'),
    ('Dublin', 'Republic of Ireland'),
    ('Florence', 'Italy'),
    ('Burges', 'Belgium'),
    ('Krakow', 'Poland'),
    ('Amsterdam', 'Holland'),
    ('Stockholm', 'Sweden'),
    ('Ljubljana', 'Slovenia'),
    ('Hanoi', 'Vietnam'),
    ('Wellington', 'New Zealand'),
    ('Nice', 'France'),
    ('Vancouver', 'Canada'),
    ('Keiv', 'Ukraine'),
    ('Hallstatt', 'Austria'),
    ('Havana', 'Cuba'),
    ('Mexico City', 'Mexico'),
    ('Beirut', 'Lebanon'),
    ('Salzburg', 'Austria'),
    ('Sao Paolo', 'Brazil'),
    ('Prague', 'Czech Republic'),
    ('Kyoto', 'Japan'),
    ('Marrakech', 'Morocco'),
    ('St Petersburg', 'Russia'),
    ('San Francisco', 'USA'),
    ('Oxford', 'UK'),
    ('Melbourne', 'Australia'),
    ('Kingston', 'Jamaica'),
    ('Amman', 'Jordan'),
    ('Lagos', 'Nigeria'),
    ('New Orleans', 'USA'),
    ('San Jose', 'Costa Rica'),
    ('Tallinn', 'Estonia'),
    ('Suva Fiji', 'Fiji'),
    ('Jarkarta', 'Indonesia'),
    ('New Delhi', 'India'),
    ('Adelaide', 'Australia'),
    ('Tripoli', 'Libya'),
    ('Male', 'Maldives'),
    ('Luxembourg', 'Luxembourg'),
    ('Kuala Lampur', 'Malaysia'),
    ('Glasgow', 'Scotland'),
    ('Valletta', 'Malta'),
    ('Kathmandu', 'Nepal'),
    ('Brussels', 'Belgium'),
    ('Panama City', 'Panama'),
    ('Bucharest', 'Romania'),
    ('Cardiff', 'Wales'),
    ('Manila', 'Phillipines'),
    ('Castries', 'Saint Lucia'),
    ('Apia', 'Samoa'),
    ('Bern', 'Switzerland'),
    ('Taipei', 'Taiwan'),
    ('Hobert', 'Australia'),
    ('Budapest', 'Hungary'),
    ('Reykjavik', 'Iceland');

INSERT INTO users(username, password)
VALUES
    ('Boby', 'blawblaw'),
    ('blaw', 'b'),
    ('other', 'dude'),
    ('baby', 'boy'),
    ('happy', 'gilmore'),
    ('busche', 'iran'),
    ('usa', 'won'),
    ('brazil', 'best'),
    ('close', 'by'),
    ('japan', 'nearby');

INSERT INTO usersToCities(userID, cityID)
VALUES
    (1, 3),
    (1, 6),
    (2, 8),
    (2, 20),
    (3, 40),
    (3, 28),
    (4, 10),
    (4, 37),
    (5, 27),
    (5, 40),
    (6, 80),
    (6, 61),
    (7, 5),
    (7, 6),
    (8, 43),
    (8, 34),
    (9, 9),
    (9, 10),
    (10, 20),
    (10, 76);
